# Generated by Django 4.2 on 2023-04-29 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('player', models.TextField()),
                ('type', models.TextField()),
                ('jersey', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('captain', models.TextField()),
                ('trophy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sixes', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wicket', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NNRG.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NNRG.teams')),
            ],
        ),
        migrations.CreateModel(
            name='points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('point', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NNRG.teams')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NNRG.teams'),
        ),
    ]
