# Generated by Django 4.2 on 2023-04-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NNRG', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='team',
            new_name='teams',
        ),
    ]
