# Generated by Django 4.2 on 2023-04-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NNRG', '0002_rename_team_players_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='teams',
            new_name='name',
        ),
    ]
