# Generated by Django 4.2 on 2023-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNRG', '0003_rename_teams_players_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='points',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='player',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='team',
            field=models.TextField(),
        ),
    ]
